PREFIX  rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbpprop:  <http://dbpedia.org/property/>
PREFIX dbpedia-owl:  <http://dbpedia.org/ontology/>

SELECT * WHERE {
  ?univName rdf:type <http://dbpedia.org/class/yago/UniversitiesAndCollegesInLosAngelesCounty,California> .
  ?univName dbpprop:type <http://dbpedia.org/resource/Private_university> .
  ?univName dbpedia-owl:numberOfStudents ?numberOfStudents .
}
ORDER BY DESC(?numberOfStudents)
LIMIT 10